name: 𓇼

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v4

    - name: git pull
      run: |-
        git pull

    - name: setup python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - name: pip caching
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/src/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: pip install
      run: |
        python -m pip install -r src/requirements.txt

    - name: update readme
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        NAME: rachel
      run: |-
        python src/build.py

    - name: push if changed
      run: |-
        git config --global user.email "rng+rng@stuy.edu"
        git config --global user.name "𓆙"

        git diff

        echo "update img"
        git diff --quiet README.md || (git add README.md && git commit -m ".")
        git diff --quiet src/etc/img.svg || (git add src/etc/img.svg && git commit -m "𓆟")

        git push
